server.port=${PORT:8080}
spring.main.banner-mode=off
azure.keyvault.secret.weather-api-key-name=${AZURE_KEY_VAULT_WEATHER_SECRET_NAME:weather-api-key}
azure.storage.container=${AZURE_STORAGE_CONTAINER:modresorts-data}
azure.servicebus.queue=${AZURE_SERVICEBUS_QUEUE:availability-checks}
